services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fusion_shop
    ports:
      - "5432:5432"
    volumes:
      - fusion_shop_db:/var/lib/postgresql/data

volumes:
  fusion_shop_db:
